# Generated by Django 4.0.6 on 2022-07-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'Premium'), ('R', 'Race'), ('S', 'Standard')], default='S', max_length=1)),
                ('price_inc', models.IntegerField(default=0)),
                ('sportbike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sportbike')),
            ],
        ),
    ]
