# Generated by Django 4.0.6 on 2022-07-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_trim_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trim',
            name='colors',
        ),
        migrations.AddField(
            model_name='sportbike',
            name='colors',
            field=models.ManyToManyField(to='main_app.colors'),
        ),
    ]
