# Generated by Django 4.0.6 on 2022-07-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_trim_colors_sportbike_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color1',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='colors',
            name='color2',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
